language: node_js
node_js:
  - "stable"

branches: 
  only:
    - develop
    - main

addons: 
  chrome: stable

before_install:
  - npm i -g npm@version-number 

before_script:
  - npm install @angular/cli
  - npm install serverless
  - serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_123" --secrete "$AWS_SECRET_ACCESS_KEY_123" --profile yash

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build -- prod
  - serverless deploy
