service: myWebsite

frameworkVersion: '2'

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: gopro.baba
      localDir: dist

  # stage: ${opt:stage, 'dev'}
  # region: ${opt:region, 'us-east-1'}
  # client: 
  #   bucketName: gopro.baba
  #   distributionFolder: dist
  #   indexDocument: index.html

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: yash

#To create bucket uncomment below
# resources:
#   Resources:
#     DemoBucketUpload:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: gopro.baba

